name: Sync to moh_client_frontend

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (qims)
        uses: actions/checkout@v3

      - name: Push to moh_client_frontend:update-production
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@github.com/qimssystem/moh_client_frontend.git target-repo
          cd target-repo

          git checkout -B update-production
          rsync -av --exclude='target-repo' ../ . --delete

          git add .
          git commit -m "Sync from qims repo [CI]" || echo "Nothing to commit"
          git push origin update-production --force

